//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fancy_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int id { get; set; }
        public string feature_title { get; set; }
        public string feature_text { get; set; }
        public string feature_img { get; set; }
        public string feature_url { get; set; }
    }
}
