//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fancy_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Latest_News
    {
        public int id { get; set; }
        public string latest_news_title { get; set; }
        public string latest_news_subtitle { get; set; }
        public string latest_news_item_title { get; set; }
        public string latest_news_item_subtitle { get; set; }
        public string latest_news_img { get; set; }
    }
}
