//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fancy_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Area
    {
        public int service_id { get; set; }
        public string service_title { get; set; }
        public string service_subtitle { get; set; }
        public string service_item_title { get; set; }
        public string service_icon { get; set; }
        public string service_item_subtitle { get; set; }
    }
}
